# Project information
site_name: 种田的黄油
site_url: https://squidfunk.github.io/mkdocs-material/
site_author: 种田的黄油
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, in 60+ languages, for all devices

# Repository
repo_name: aizawaayame
repo_url: https://github.com/aizawaayame

# Copyright
copyright: Copyright &copy; 2021 - 2025 taneda no bata

theme:
  name: material
  custom_dir: 'material/templates'
  features:
  - announce.dismiss
  # - content.action.edit
  # - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.code.select
  # - content.footnote.tooltips
  # - content.tabs.link
  - content.tooltips
  # - header.autohide
  # - navigation.expand
  - navigation.footer
  - navigation.indexes
  # - navigation.instant
  # - navigation.instant.prefetch
  # - navigation.instant.progress
  # - navigation.prune
  - navigation.sections
  - navigation.tabs
  # - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  # - toc.integrate

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  logo: assets/images/favicon.png
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.blocks.caption

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocs-material/
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/squidfunk.bsky.social
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/squidfunk

extra_css:
  - '_static/css/extra.css?v=16'

extra_javascript:
  - _static/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - About: index.md
  - C++:
    - 语法:
      - 关键字:
        - C++/语法/关键字/sizeof.md
        - C++/语法/关键字/static.md
        - C++/语法/关键字/const.md
        - C++/语法/关键字/nullptr.md
      - 对象和类:
        - C++/语法/对象和类/this指针.md
    - 编译器:
      - 编译器优化:
        - C++/编译器/编译器优化/拷贝省略、RVO、NRVO优化策略.md
  - UE:
    - Core:
      - Physics:
        - UE/Core/Physics/轴向.md
      - GC:
        - UE/Core/GC/UE垃圾回收概述和应用.md
    - Framework:
      - Actor:
        - UE/Framework/Actor/Actor.md
      - Camera:
        - UE/Framework/Camera/相机系统.md
    - Network:
      - UE/Network/Actor Role and Remote Role.md
  - Project:
    - UE:
      - OnaGameSample:
        - Project/UE/OnaGameSample/走跑混合.md
        - Project/UE/OnaGameSample/攀爬.md
        - Project/UE/OnaGameSample/相机模块设计.md
  - Reference:
    - Reference/Build-In/index.md
    - Reference/Build-In/Admonition.md
    - Reference/Build-In/Annotation.md
    - Reference/Build-In/Code Block.md
    - Reference/Build-In/Content Tab.md
    - Reference/Build-In/Footnote.md
    - Reference/Build-In/Formatting.md
    - Reference/Build-In/Grid.md
    - Reference/Build-In/Icon.md
  - Blog:
    - blog/index.md
